class Commands:
    LEECH = "leech@Ai_Leech1Bot"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status@Ai_Leech1Bot"
    SETTINGS = "settings@Ai_Leech1Bot"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl@Ai_Leech1Bot"
    PYTDL = "pytdl@Ai_Leech1Bot"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "server"
    USERSETTINGS = "usetting"
    INSTADL = "instadl@Ai_Leech1Bot"
